// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot.subsystems;


import frc.robot.Robot;
import frc.robot.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.shuffleboard.Shuffleboard;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.PIDOutput;
import edu.wpi.first.wpilibj.PIDSource;

import com.ctre.phoenix.motorcontrol.ControlMode;
import com.ctre.phoenix.motorcontrol.FeedbackDevice;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class Shooter extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    boolean enabled = false;
    private double kF = 0.0;
    private double kP = 0.0;
    private double kI = 0.0;
    private double kD = 0.0;
    private double kMaxRPM = 2530;

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
private WPI_TalonSRX shooterMotor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public Shooter() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    shooterMotor = new WPI_TalonSRX(10);
        
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    shooterMotor.configFactoryDefault();
    shooterMotor.configSelectedFeedbackSensor(FeedbackDevice.QuadEncoder);
    shooterMotor.config_kF(0, kF, 10);
    shooterMotor.config_kP(0, kP, 10);
    shooterMotor.config_kI(0, kI, 10);
    shooterMotor.config_kD(0, kD, 10);

    }

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new ShooterControl());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop
        //Update motor speed here IF SHOOTER IS ON
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void toggleShooter() {
        if(enabled){
            enabled = false;
            SmartDashboard.putString("Shooter", "Shooter Disabled");
            shooterMotor.set(0);
        } else {
            enabled = true;
            SmartDashboard.putString("Shooter", "Shooter Enabled");
        }
    }

    //Method that updates the shooter motor speed
    public void updateMotorSpeed(double paddlePos){
        if((paddlePos < 0) || (paddlePos > 1)) {
            SmartDashboard.putString("ShooterMotor", "Shooter: can't set motor speed to " + paddlePos);
            return;
            //limits of motorSpeed are 0 and max rpm times ticks per revolution
        }

        if (enabled == true){
            double motorspeed_per_100ms = kMaxRPM*paddlePos*409.6; //Motor Speed per 100 Milliseconds
            shooterMotor.set(ControlMode.Velocity, motorspeed_per_100ms);
            SmartDashboard.putString("ShooterMotor", "Shooter: motor speed is " + shooterMotor.getSelectedSensorVelocity(0));
            SmartDashboard.putNumber("Desired RPM", kMaxRPM*paddlePos);
            //ControlMode.Velocity uses the built-in PID error corection in the motor controller
        }
    }
}
